language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
install:
  - cd local_plugins/search
  - npm link search
  - cd ../../
  - npm install
script:
  - node .
before_deploy:
  - cd public
  - echo "alansartlog.com" > CNAME
  - cd ../ #they are indeed important
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  target_branch: gh-pages
  local_dir: public